name: flutter_image_picker_ios
description: iOS implementation of the image_picker plugin.
repository: https://github.com/one-memory-a-day/flutter-image-picker/tree/main/image_picker_ios

version: 1.0.4

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

flutter:
  plugin:
    implements: image_picker
    platforms:
      ios:
        dartPluginClass: ImagePickerIOS
        pluginClass: FLTImagePickerPlugin

dependencies:
  flutter:
    sdk: flutter
  image_picker_platform_interface: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.4.4
  pigeon: ^17.0.0

topics:
  - camera
  - image-picker
  - files
  - file-selection
